# Server
server.port=8081

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/wood_company
spring.datasource.username=postgres
spring.datasource.password=19122001
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=wood_company_super_secret_key_change_this_in_production_2024
jwt.expiration=604800000
